// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment_request.proto
// Protobuf Java Version: 4.29.0

package proto;

public final class PaymentRequestProtos {
  private PaymentRequestProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      PaymentRequestProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaymentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PaymentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    java.lang.String getTransactionId();
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();

    /**
     * <code>string payer_name = 2;</code>
     * @return The payerName.
     */
    java.lang.String getPayerName();
    /**
     * <code>string payer_name = 2;</code>
     * @return The bytes for payerName.
     */
    com.google.protobuf.ByteString
        getPayerNameBytes();

    /**
     * <code>string payee_name = 3;</code>
     * @return The payeeName.
     */
    java.lang.String getPayeeName();
    /**
     * <code>string payee_name = 3;</code>
     * @return The bytes for payeeName.
     */
    com.google.protobuf.ByteString
        getPayeeNameBytes();

    /**
     * <code>double amount = 4;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>string currency = 5;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 5;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>string payment_date = 6;</code>
     * @return The paymentDate.
     */
    java.lang.String getPaymentDate();
    /**
     * <code>string payment_date = 6;</code>
     * @return The bytes for paymentDate.
     */
    com.google.protobuf.ByteString
        getPaymentDateBytes();
  }
  /**
   * Protobuf type {@code proto.PaymentRequest}
   */
  public static final class PaymentRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.PaymentRequest)
      PaymentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        PaymentRequest.class.getName());
    }
    // Use PaymentRequest.newBuilder() to construct.
    private PaymentRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PaymentRequest() {
      transactionId_ = "";
      payerName_ = "";
      payeeName_ = "";
      currency_ = "";
      paymentDate_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.PaymentRequestProtos.internal_static_proto_PaymentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.PaymentRequestProtos.internal_static_proto_PaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.PaymentRequestProtos.PaymentRequest.class, proto.PaymentRequestProtos.PaymentRequest.Builder.class);
    }

    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object transactionId_ = "";
    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    @java.lang.Override
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYER_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object payerName_ = "";
    /**
     * <code>string payer_name = 2;</code>
     * @return The payerName.
     */
    @java.lang.Override
    public java.lang.String getPayerName() {
      java.lang.Object ref = payerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payerName_ = s;
        return s;
      }
    }
    /**
     * <code>string payer_name = 2;</code>
     * @return The bytes for payerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayerNameBytes() {
      java.lang.Object ref = payerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYEE_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object payeeName_ = "";
    /**
     * <code>string payee_name = 3;</code>
     * @return The payeeName.
     */
    @java.lang.Override
    public java.lang.String getPayeeName() {
      java.lang.Object ref = payeeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payeeName_ = s;
        return s;
      }
    }
    /**
     * <code>string payee_name = 3;</code>
     * @return The bytes for payeeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayeeNameBytes() {
      java.lang.Object ref = payeeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private double amount_ = 0D;
    /**
     * <code>double amount = 4;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currency_ = "";
    /**
     * <code>string currency = 5;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 5;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMENT_DATE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object paymentDate_ = "";
    /**
     * <code>string payment_date = 6;</code>
     * @return The paymentDate.
     */
    @java.lang.Override
    public java.lang.String getPaymentDate() {
      java.lang.Object ref = paymentDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentDate_ = s;
        return s;
      }
    }
    /**
     * <code>string payment_date = 6;</code>
     * @return The bytes for paymentDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPaymentDateBytes() {
      java.lang.Object ref = paymentDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, transactionId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, payerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payeeName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, payeeName_);
      }
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        output.writeDouble(4, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, currency_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(paymentDate_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, paymentDate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, transactionId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, payerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payeeName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, payeeName_);
      }
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, currency_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(paymentDate_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, paymentDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.PaymentRequestProtos.PaymentRequest)) {
        return super.equals(obj);
      }
      proto.PaymentRequestProtos.PaymentRequest other = (proto.PaymentRequestProtos.PaymentRequest) obj;

      if (!getTransactionId()
          .equals(other.getTransactionId())) return false;
      if (!getPayerName()
          .equals(other.getPayerName())) return false;
      if (!getPayeeName()
          .equals(other.getPayeeName())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getCurrency()
          .equals(other.getCurrency())) return false;
      if (!getPaymentDate()
          .equals(other.getPaymentDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionId().hashCode();
      hash = (37 * hash) + PAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPayerName().hashCode();
      hash = (37 * hash) + PAYEE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPayeeName().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      hash = (37 * hash) + PAYMENT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.PaymentRequestProtos.PaymentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.PaymentRequestProtos.PaymentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.PaymentRequestProtos.PaymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.PaymentRequestProtos.PaymentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PaymentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PaymentRequest)
        proto.PaymentRequestProtos.PaymentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.PaymentRequestProtos.internal_static_proto_PaymentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.PaymentRequestProtos.internal_static_proto_PaymentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.PaymentRequestProtos.PaymentRequest.class, proto.PaymentRequestProtos.PaymentRequest.Builder.class);
      }

      // Construct using proto.PaymentRequestProtos.PaymentRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        transactionId_ = "";
        payerName_ = "";
        payeeName_ = "";
        amount_ = 0D;
        currency_ = "";
        paymentDate_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.PaymentRequestProtos.internal_static_proto_PaymentRequest_descriptor;
      }

      @java.lang.Override
      public proto.PaymentRequestProtos.PaymentRequest getDefaultInstanceForType() {
        return proto.PaymentRequestProtos.PaymentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proto.PaymentRequestProtos.PaymentRequest build() {
        proto.PaymentRequestProtos.PaymentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.PaymentRequestProtos.PaymentRequest buildPartial() {
        proto.PaymentRequestProtos.PaymentRequest result = new proto.PaymentRequestProtos.PaymentRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.PaymentRequestProtos.PaymentRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.transactionId_ = transactionId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.payerName_ = payerName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payeeName_ = payeeName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.amount_ = amount_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.currency_ = currency_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.paymentDate_ = paymentDate_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.PaymentRequestProtos.PaymentRequest) {
          return mergeFrom((proto.PaymentRequestProtos.PaymentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.PaymentRequestProtos.PaymentRequest other) {
        if (other == proto.PaymentRequestProtos.PaymentRequest.getDefaultInstance()) return this;
        if (!other.getTransactionId().isEmpty()) {
          transactionId_ = other.transactionId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPayerName().isEmpty()) {
          payerName_ = other.payerName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPayeeName().isEmpty()) {
          payeeName_ = other.payeeName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getPaymentDate().isEmpty()) {
          paymentDate_ = other.paymentDate_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                transactionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                payerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                payeeName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                amount_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 42: {
                currency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                paymentDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object transactionId_ = "";
      /**
       * <code>string transaction_id = 1;</code>
       * @return The transactionId.
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return The bytes for transactionId.
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        transactionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionId() {
        transactionId_ = getDefaultInstance().getTransactionId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The bytes for transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        transactionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object payerName_ = "";
      /**
       * <code>string payer_name = 2;</code>
       * @return The payerName.
       */
      public java.lang.String getPayerName() {
        java.lang.Object ref = payerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payer_name = 2;</code>
       * @return The bytes for payerName.
       */
      public com.google.protobuf.ByteString
          getPayerNameBytes() {
        java.lang.Object ref = payerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payer_name = 2;</code>
       * @param value The payerName to set.
       * @return This builder for chaining.
       */
      public Builder setPayerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        payerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string payer_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayerName() {
        payerName_ = getDefaultInstance().getPayerName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string payer_name = 2;</code>
       * @param value The bytes for payerName to set.
       * @return This builder for chaining.
       */
      public Builder setPayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        payerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object payeeName_ = "";
      /**
       * <code>string payee_name = 3;</code>
       * @return The payeeName.
       */
      public java.lang.String getPayeeName() {
        java.lang.Object ref = payeeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payeeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payee_name = 3;</code>
       * @return The bytes for payeeName.
       */
      public com.google.protobuf.ByteString
          getPayeeNameBytes() {
        java.lang.Object ref = payeeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payeeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payee_name = 3;</code>
       * @param value The payeeName to set.
       * @return This builder for chaining.
       */
      public Builder setPayeeName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        payeeName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string payee_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayeeName() {
        payeeName_ = getDefaultInstance().getPayeeName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string payee_name = 3;</code>
       * @param value The bytes for payeeName to set.
       * @return This builder for chaining.
       */
      public Builder setPayeeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        payeeName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 4;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 4;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {

        amount_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 5;</code>
       * @return The currency.
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 5;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 5;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currency_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        currency_ = getDefaultInstance().getCurrency();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 5;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currency_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object paymentDate_ = "";
      /**
       * <code>string payment_date = 6;</code>
       * @return The paymentDate.
       */
      public java.lang.String getPaymentDate() {
        java.lang.Object ref = paymentDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          paymentDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payment_date = 6;</code>
       * @return The bytes for paymentDate.
       */
      public com.google.protobuf.ByteString
          getPaymentDateBytes() {
        java.lang.Object ref = paymentDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payment_date = 6;</code>
       * @param value The paymentDate to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        paymentDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string payment_date = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentDate() {
        paymentDate_ = getDefaultInstance().getPaymentDate();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string payment_date = 6;</code>
       * @param value The bytes for paymentDate to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        paymentDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.PaymentRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.PaymentRequest)
    private static final proto.PaymentRequestProtos.PaymentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.PaymentRequestProtos.PaymentRequest();
    }

    public static proto.PaymentRequestProtos.PaymentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentRequest>
        PARSER = new com.google.protobuf.AbstractParser<PaymentRequest>() {
      @java.lang.Override
      public PaymentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaymentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.PaymentRequestProtos.PaymentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PaymentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PaymentRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025payment_request.proto\022\005proto\"\210\001\n\016Payme" +
      "ntRequest\022\026\n\016transaction_id\030\001 \001(\t\022\022\n\npay" +
      "er_name\030\002 \001(\t\022\022\n\npayee_name\030\003 \001(\t\022\016\n\006amo" +
      "unt\030\004 \001(\001\022\020\n\010currency\030\005 \001(\t\022\024\n\014payment_d" +
      "ate\030\006 \001(\tB\026B\024PaymentRequestProtosb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PaymentRequest_descriptor,
        new java.lang.String[] { "TransactionId", "PayerName", "PayeeName", "Amount", "Currency", "PaymentDate", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
